### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by StrykerDG** [StrykerDG/StrykerDG.FarmForge#1]
Provide Documentation for the following activities:

PR Submission
Issue / Feature Submission
Device Submission
Setup & Installation
- [x] 8 - Create architecture diagram
- [x] [Create Documentation Website](https://app.gitkraken.com/glo/card/a6e03051aba64df895b71b12191a76b8)
- [x] [Create / Modify Docusaurus files](https://app.gitkraken.com/glo/card/49367c732f5f4b39b755068ec2b1390a)
- [x] [Update Project Readme](https://app.gitkraken.com/glo/card/07c0c2a76d504ae7a2f85c325c29e6c6)
