### ISSUE TITLE
FarmForge Web Client

### ISSUE THREAD

**Issue by StrykerDG** [StrykerDG/StrykerDG.FarmForge#12]
Build a web client where the user can interact with their FarmForge System
- [x] #17 - Logging System
- [x] #19 - Inventory System
- [x] #21 - Users should be able to log into the FarmForge web client
- [x] #22 - Users should be able to add / remove / modify accounts
- [x] [Web Client should be mobile friendly and responsive](https://app.gitkraken.com/glo/card/ef47b8224aa945359c29396524bc7c0b)
- [x] [Users should be able to configure settings](https://app.gitkraken.com/glo/card/36aad3acc3fc4b5aa47638b53bab9ad6)
- [x] [Implement text search / filtering for Crops](https://app.gitkraken.com/glo/card/d0c3591d1a8c4623b2d4d3f7840735de)
- [x] [Implement date search for Crops](https://app.gitkraken.com/glo/card/20f23e12d56140e1850013cf5718e26c)
- [x] [Hide unused work areas](https://app.gitkraken.com/glo/card/f5e87309aafc441aa91b7f2607f6e453)
- [x] [Create Cards for dashboard](https://app.gitkraken.com/glo/card/f5f6135a627143e79ef52ce1e89c271e)
- [x] #112 - Polish styling on the default modal
- [x] #110 - Refactor to remove "magic numbers"

**Comment by StrykerDG** [comment]
Logging system will only have crop logging for MVP. Inventory system will move to another task / milestone
