### ISSUE TITLE
Order Management

### ISSUE THREAD

**Issue by StrykerDG** [StrykerDG/StrykerDG.FarmForge#178]
- [ ] [Ability to create order](https://app.gitkraken.com/glo/card/9c3fd5f117174a178cb32a48611bf6a0)
- [ ] [Ability to make payment for order](https://app.gitkraken.com/glo/card/52b4f9f37d024f298384bad899c5084f)
- [ ] [Orders complete once paid](https://app.gitkraken.com/glo/card/bdf42fb6b9c046768e7e20cce273e3fa)
- [ ] [Attach Crops (inventory) and Customers to an order](https://app.gitkraken.com/glo/card/03284848fba04cabbfa431cfdf2e4d46)
- [ ] [Create customers](https://app.gitkraken.com/glo/card/1235ac1212ca4c4982944726641c4f7d)
- [ ] [Update Customers](https://app.gitkraken.com/glo/card/a90bdbcfd5644a498be6d398a0e7abf4)
- [ ] [Customer Screen / Work Area](https://app.gitkraken.com/glo/card/a5ee2e459ce34b0aae41cc0b40de292e)
- [ ] [Order/Sales Screen / Work Area](https://app.gitkraken.com/glo/card/c819c06133d342308f0aa442ba9307dc)
