### ISSUE TITLE
Device Template

### ISSUE THREAD

**Issue by StrykerDG** [StrykerDG/StrykerDG.FarmForge#2]
Create a template that others can use when designing their own FarmForge devices
- [ ] #3 - Create a circuit diagram for the device template
- [x] #4 - Add DHT to device template
- [x] #5 - Send Responses from BaseDevice.ino to index.js
- [ ] #6 - Connect Device Template to FarmForge.Api
- [ ] #10 - Create README for Device Template
