### ISSUE TITLE
Users should be able to log into the FarmForge web client

### ISSUE THREAD

**Issue by StrykerDG** [StrykerDG/StrykerDG.FarmForge#21]
- [x] #27 - Implement authentication in API
- [x] #28 - Add user tables to data model and migration
- [x] #32 - Create standard API response object
